### ISSUE TITLE
Release v0.2 : New Website Features

### ISSUE THREAD

**Issue by duttakapil** [coderplex-org/coderplex-org#2]
**Deadline**:  27th Feb  
[GitHub Issue Link](https://github.com/coderplex-org/coderplex-org/issues/2)

---

**23rd Feb, 2021**  
- [x] Setup beta environment  
- [x] Expand the height of the goal sidebar  
- [x] Code syntax highlighter  
- [x] Change color of code in dark mode  
- [x] Remove vertical line connecting comments  
- [x] Limit char on bio display in /members page  

**24th Feb, 2021**  
- [x] Edit and delete updates from Home Page  

**25th Feb, 2021**  
- [x] Edit and delete comments   
- [x] Like feature for comments  

**26th Feb, 2021**  
- [x] Show the total number of users in the community  
- [x] Deadline for goals   

**27th Feb, 2021**  
- [x] See who liked the posts   
- [x] Optimize Follow and like button slowness

**28th Feb, 2021**  
- [x] Notifications   
- [x] Favicons with transparent background   
- [x] Title and Copy change  
- [x] Add a way to dismiss the goal preview on the home page.  
- [x] Add mdx embeds for popular platforms.  
- [x] Bug Report  
- [x] Do not re-fetch the entire feed whenever an update/comment is added/edited/deleted.  
- [x] Add a reply button to the comment.   
- [x] Show the notifications in reverse order (latest notification at the top)  
- [x] Show the indicator in the bell icon whenever a new notification comes  
- [x] Show the indicator for unread notifications.

**Comment by pbteja1998** [comment]
`v0.2` released at https://github.com/coderplex-org/coderplex-org/releases/tag/v0.2
